version: '3.8'

services:
  icp-dev-env:
    image: ghcr.io/dfinity/icp-dev-env:latest
    container_name: icp-dev-env-win
    platform: linux/x86_64
    working_dir: /root/app
    volumes:
      - .:/root/app
    command: tail -f /dev/null
    ports:
      - "4943:4943"  # Map container port to host
    environment:
      - DFX_NETWORK_HOST=0.0.0.0  # Allow external connections
    networks:
      - icp_network
networks:
  icp_network:
    driver: bridge